Rename file, check for gradle project (broken)

diff --git a/buildapk b/buildapk
--- a/buildapk
+++ b/buildapk
@@ -5,15 +5,18 @@ INPUT_DIR=$(pwd)
 OUTPUT_DIR="gen"
 OUTPUT_FILE="app.apk"
 
-CONFIGURE="false"
+GRADLE="false"
 
 show_full_help() {
+    echo
     echo "usage: buildapk [-d input dir][-o output dir][-f output file][-j android jar]"
-    echo 
+    echo
     echo "Compile and package android applications."
+    echo
     echo "Example:"
-    echo " - buildapk -d /sdcard/app -o build -f lol.apk -j /sdcard/lol/android.jar"
-    echo "(None of the aguments required - just execute from same dir as AndroidManifest.xml"
+    echo "   buildapk -d /sdcard/app -o build -f lol.apk -j /sdcard/lol/android.jar"
+    echo
+    echo "(None of the aguments required - just execute from same dir as AndroidManifest.xml)"
 }
 
 show_help() {
@@ -21,31 +24,21 @@ show_help() {
 }
 
 set_in_directory() {
-    CONFIGURE="true"
-    echo -n "Setting input directory to $1..."
     INPUT_DIR=$1
-    echo "done"
+
 }
 
 set_out_directory() {
-    CONFIGURE="true"
-    echo -n "Setting output directory to $1..."
     OUTPUT_DIR=$1
-    echo "done"
+
 }
 
 set_out_file() {
-    CONFIGURE="true"
-    echo -n "Setting output file name to $1..."
     OUTPUT_FILE=$1
-    echo "done"
 }
 
 set_jar_path() {
-    CONFIGURE="true"
-    echo -n "Setting path of android.jar to $1..."
     ANDROID_JAR=$1
-    echo "done"
 }
    
 do_build() {
@@ -69,6 +62,12 @@ do_build() {
     echo "#########################"
     echo "     Starting Build      "
     echo "#########################"
+    
+    if [ -f  ]; then
+        GRADLE="true"
+        echo "Gradle project detected."
+        echo 
+    fi
     
     echo -n "Creating R.java..."
     if [ ! -f "$INPUT_DIR/AndroidManifest.xml" ]; then
@@ -98,15 +97,11 @@ do_build() {
     echo "https://github.com/TheDiamondYT1/termux-buildapk"
 }
 
-echo
-echo "#########################"
-echo "       Configuring       "
-echo "#########################"
-
 while getopts ":h:d:o:f:j:" o; do
     case "${o}" in
         h)
-            show_full_help;;
+            show_full_help
+            exit 1;;
         d)
             set_in_directory ${OPTARG};;
         o)
@@ -121,10 +116,6 @@ while getopts ":h:d:o:f:j:" o; do
             exit 1;;
     esac
 done
-
-if [ $CONFIGURE = "false" ]; then
-    echo "Nothing to configure."
-fi
 
 echo 
 do_build
